### ISSUE TITLE
Button block needed

### ISSUE THREAD

**Issue by catymcclure** [pixelcollective/dreamdefenders.org#105]
# Overview

Site needs a button block.

## Current Behavior

Site has no button block. Thus crucial linked content is easy to miss on posts.

## Desired Behavior

The editor would have a button block.

## Related information/Designs

- [On this post](https://build.dreamdefenders.tinypixel.dev/projects/the-peoples-covid-bailout/?preview_id=640&preview_nonce=fa4d50c5c7&preview=true) you can see where large button blocks would be needed to highlight the links to COVID-19 assistance resources 

## Acceptance Criteria

- [x] Button block exists and functions as expected

**Comment by kellymears** [comment]
donezo
