### ISSUE TITLE
Cover block overlay is in front of text on frontend

### ISSUE THREAD

**Issue by catymcclure** [pixelcollective/dreamdefenders.org#111]
## Describe the bug

When applying an overlay to a cover block, it covers the text too; i.e. the overlay is at the front of the z index and needs to move back one spot. Issue occurs on frontend only.

### Editor view:
![Screen Shot 2020-04-13 at 1.42.23 PM.png](https://images.zenhubusercontent.com/5e8fa47d8bea5741f4e91d21/4002e6fc-e43b-4fb1-86da-8e6f322bd045)

### Front view:
![Screen Shot 2020-04-13 at 1.43.02 PM.png](https://images.zenhubusercontent.com/5e8fa47d8bea5741f4e91d21/7f7eb6a0-294d-47e1-b165-35e0071ce0f7)

**Comment by kellymears** [comment]
this is done and a valid issue with the `core/cover` block. 

However, please use the site-specific `Banner` block for this use-case.
