### ISSUE TITLE
Join link in menu bar pulls up lightbox with form on some pages

### ISSUE THREAD

**Issue by catymcclure** [pixelcollective/dreamdefenders.org#117]
## Describe the bug

The Join link in the top nav still pulls up a lightbox with a placeholder for an embed form. This happens sitewide **except** the home page. 

## Suggested solutions

Could keep the lightbox, replacing form placeholder with a Join link to actblue and replacing the 305 Miami image with the shield, which would be less disorienting for users.

Or could just make the Join button link out to the actblue form.

## Additional context

On the homepage, hovering over the Join link shows that it has the correct link associated with it, but when you click it, nothing happens. 

Seems relevant: I tried using the Customizer to change the Join link. These changes were published.

![Screen Shot 2020-04-15 at 12.30.20 PM.jpg](https://images.zenhubusercontent.com/5e8fa47d8bea5741f4e91d21/710da215-5617-4737-b467-d2bec50d9620)

**Comment by kellymears** [comment]
this should be fixed by https://github.com/pixelcollective/dreamdefenders.org/commit/71024b0105aad565f94d43a54cf4a7a729efde80

**Comment by kellymears** [comment]
deploying https://github.com/pixelcollective/dreamdefenders.org/runs/590129056
