### ISSUE TITLE
Complete blockquote blocks

### ISSUE THREAD

**Issue by catymcclure** [pixelcollective/dreamdefenders.org#50]
# Overview

This issue tracks progress on the two blockquote blocks: "blockquote left" and "blockquote large."

## Related information/Designs

- [Design mockups](https://xd.adobe.com/view/49232e42-1e44-4df8-70aa-a53d63a6fcaa-3f12/grid)

## Acceptance Criteria

- [x] Blockquote left displays as expected
- [x] Blockquote large displays as expected
- [x] Blocks are responsive

**Comment by kellymears** [comment]
closed by 2a8071297bd3b0ced964d0434da5f5441a0e2639.
