### ISSUE TITLE
Complete Instagram block

### ISSUE THREAD

**Issue by catymcclure** [pixelcollective/dreamdefenders.org#53]
# Overview

This issue tracks progress on the Instagram block.

## Related information/Designs

- [Homepage mockup](https://xd.adobe.com/view/49232e42-1e44-4df8-70aa-a53d63a6fcaa-3f12/screen/02afb207-d012-4b0d-af8d-edf324ffa2fe/Home-on-scroll-2)

## Acceptance Criteria

- [x] Instagram posts are pulled as expected
- [x] Block is responsive
- [x] Yellow "@dreamdefenders" ribbon displays as expected

**Comment by kellymears** [comment]
Closed by https://github.com/pixelcollective/dreamdefenders.org/commit/9e2d79237e17533a7af520ead0365fe758df15ac
