### ISSUE TITLE
No Styling on Hyperlinks

### ISSUE THREAD

**Issue by catymcclure** [pixelcollective/dreamdefenders.org#89]
## Describe the bug

On frontend, hyperlinked text has no styling to differentiate between links and regular text. This occurs on frontend only.

### Links

[This page](https://build.dreamdefenders.tinypixel.dev/projects/the-peoples-covid-bailout/) has two headlines, Volunteer to Keep Your Community Safe and Find What You Need. They are both hyperlinked, but have no styling.

## Screenshots
In this shot, the top two headlines are links, and the third headline is not.
![Screen Shot 2020-04-06 at 1 18 36 PM (2)](https://user-images.githubusercontent.com/36547122/78601185-2dffd080-7809-11ea-893c-d10badeea26a.png)

Here is a screenshot of the links on the backend.
![Screen Shot 2020-04-06 at 1 23 34 PM](https://user-images.githubusercontent.com/36547122/78601553-d57d0300-7809-11ea-8839-103a9a098288.png)

### Expected behavior

Hyperlinked text styling should appear on frontend as well as backend.

**Comment by kellymears** [comment]
fixed in https://github.com/pixelcollective/dreamdefenders.org/commit/7964d89f619c7ea50fe55fb02994b402acf33cb0
